version: '3.8'

services:
  flint_docs:
    build: 
      context: ..
      dockerfile: ./Dockerfile
    ports:
      - "3030:3030"
    env_file:
      - .env
    environment:
      - FLINT_HOT=0
      - PORT=3030
    restart: unless-stopped
