name: flint_docs
description: A FlintDart application
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flint_dart: ^1.0.0+29
   


dependency_overrides:
  flint_dart:
    path: ../flint_dart
  mysql_dart:
    git:
      url: https://github.com/Hybiekay/mysql.dart
      ref: main
